#include <string>
#include "tokenconsts.h"

using std::string;

static const char* getTokenName(int token) {
  string ret;
  switch (token) {
    case yand:
      return "yand";
    case yarray:
      return "yarray";
    case yassign:
      return "yassign";
    case ybegin:
      return "ybegin";
    case ycaret:
      return "ycaret";
    case ycase:
      return "ycase";
    case ycolon:
      return "ycolon";
    case ycomma:
      return "ycomma";
    case yconst:
      return "yconst";
    case ydispose:
      return "ydispose";
    case ydiv:
      return "ydiv";
    case ydivide:
      return "ydivide";
    case ydo:
      return "ydo";
    case ydot:
      return "ydot";
    case ydotdot:
      return "ydotdot";
    case ydownto:
      return "ydownto";
    case yelse:
      return "yelse";
    case yend:
      return "yend";
    case yequal:
      return "yequal";
    case yfalse:
      return "yfalse";
    case yfor:
      return "yfor";
    case yfunction:
      return "yfunction";
    case ygreater:
      return "ygreater";
    case ygreaterequal:
      return "ygreaterequal";
    case yident:
      return "yident";
    case yif:
      return "yif";
    case yin:
      return "yin";
    case yleftbracket:
      return "yleftbracket";
    case yleftparen:
      return "yleftparen";
    case yless:
      return "yless";
    case ylessequal:
      return "ylessequal";
    case yminus:
      return "yminus";
    case ymod:
      return "ymod";
    case ymultiply:
      return "ymultiply";
    case ynew:
      return "ynew";
    case ynil:
      return "ynil";
    case ynot :
      return "ynot ";
    case ynotequal:
      return "ynotequal";
    case ynumber:
      return "ynumber";
    case yof:
      return "yof";
    case yor:
      return "yor";
    case yplus:
      return "yplus";
    case yprocedure:
      return "yprocedure";
    case yprogram:
      return "yprogram";
    case yread:
      return "yread";
    case yreadln:
      return "yreadln";
    case yrecord:
      return "yrecord";
    case yrepeat:
      return "yrepeat";
    case yrightbracket:
      return "yrightbracket";
    case yrightparen:
      return "yrightparen";
    case ysemicolon:
      return "ysemicolon";
    case yset:
      return "yset";
    case ystring: 
      return "ystring";
    case ythen:
      return "ythen";
    case yto:
      return "yto";
    case ytrue:
      return "ytrue";
    case ytype:
      return "ytype";
    case yuntil:
      return "yuntil";
    case yvar:
      return "yvar";
    case ywhile:
      return "ywhile";
    case ywrite:
      return "ywrite";
    case ywriteln:
      return "ywriteln";
    case yunknown:
      return "yunknown";
    default:
      return "";
  }
}
